### ISSUE TITLE
Diagrama de casos de uso

### ISSUE THREAD

**Issue by FilipeFlip** [renansilva15/doe-aqui#7]
Criação do diagrama de casos de uso, para descrição dos atores e funcionalidades do sistema.

Link Docs (Comentários):
https://docs.google.com/document/d/1XV15vqo-jGBZFpqFdXMSZED7yaVDt_RZZg1Cp-oVbTc/edit?usp=sharing

**Comment by devrenangabriel** [comment]
Show meu nobre
